version: "3"

services:
  nestjs-template: #TODO: Change this to your project name
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs_template # TODO: Change this to your project name
    ports:
      - "7000:3000"
    restart: always
    env_file:
      - ./.env